# Konfigurasi Environment Railway (Laravel + Inertia)
[phases.setup]

# Installation
nixPkgs = ['php82', 'php82Extensions.pdo_mysql', 'php82Extensions.bcmath', 'php82Extensions.fileinfo', 'php82Extensions.tokenizer', 'php82Extensions.mbstring', 'php82Extensions.dom', 'php82Extensions.xml', 'nodejs_20', 'npm-9_x', 'composer']

[phases.build]
cmds = [
    'npm install',
    'npm run build',
    'composer install --ignore-platform-reqs --no-dev --optimize-autoloader'
]

[start]

cmd = 'sh start.sh'
